import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/login n signin/Profile-setup.module.css'
import { useState } from 'react';
import { useFormik } from 'formik';
import { useRouter } from 'next/router';

export default function Merchant() {
    
  const router = useRouter();

  const [nama, setName] = useState("");
  const [email, setEmail] = useState("");
  const [kota, setKota] = useState("");

  const handler = async (e) => {
    e.preventDefault();

    let n = nama;
    let em = email;
    let k = kota;

    console.log(nama,email,kota)

    const options = {
        method:"POST",
        headers:{'Content-Type':'application/json'},
        body:JSON.stringify({nama:n, email:em, kota:k})
    }
  
    await fetch('http://localhost:3000/api/auth/data-diri', options)
        .then(res=>res.json())
        .then((datas)=>{
          console.log(datas);
          if(datas.status)router.push('http://localhost:3000/daftar/merchant/data-usaha');
          else alert(datas.message);
        })
  
  }


    return (
        <>
        <Head>
            <title>GetPartner</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
        <div class=" box position-relative">
            <div class="position-absolute top-50 start-50 translate-middle">
                <div className={styles.logo}>
                    <Image 
                    src="/aset/login n signin aset/Getjob.svg" 
                    alt="logo"
                    width={150}
                    height={50}
                    />
                </div>

                <div className={styles.title}>
                    <p>
                        Anda Mendaftar Sebagai
                        <br/>
                        <span className={styles.highlight}>Merchant</span>
                        <br/>
                        <br/>
                        Isi Data Diri Anda
                    </p>
                </div>

                <div className={styles.setup_main}>
                    <div className="merchant_field">
                        <input 
                        type="text" 
                        className={styles.setup_input} 
                        placeholder="Nama Lengkap"
                        onChange={(e) => setName(e.target.value)}
                        />
                    </div>

                    <div className="merchant_field">
                        <input 
                        type="text" 
                        className={styles.setup_input} 
                        placeholder="Alamat Email"
                        onChange={(e) => setEmail(e.target.value)}
                        />
                    </div>

                    <div class="input-group mb-3" className={styles.non_text_group}>
                        <select 
                        class="form-select" 
                        className={styles.setup_select} 
                        id="inputGroupSelect01"
                        onChange={(e) => setKota(e.target.value)}
                        >
                            <option selected>Pilih Kota</option>
                            <option value="1">Jakarta</option>
                            <option value="2">Yogyakarta</option>
                            <option value="3">Solo</option>
                        </select>
                    </div>
            
                    <div class="input-group mb-3" className={styles.non_text_group}>
                        <label className={styles.non_text_group_text}>Foto KTP</label>
                        <input type="file" accept="image/*" className={styles.setup_upload}/>
                    </div>
            
                    <div className="buttons">
                        <Link href="/daftar/merchant/data-usaha"><button className={styles.setup_next_btn} onClick={(e) => handler(e)}>Lanjutkan</button></Link>
                    </div>
                </div>
            </div>
        </div>
        </main>
        </>
    )
}