import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/login n signin/Profile-setup.module.css'
import { useState } from 'react';
import { useFormik } from 'formik';
import { useRouter } from 'next/router';
import { getSession, useSession, signOut } from "next-auth/react"

export default function Merchant() {

    const router = useRouter();

    const [namaresto, setResto] = useState("");
    const [alamat, setAlamat] = useState("");
    const [jenis, setJenis] = useState("");
  
    const handler = async (e) => {
      e.preventDefault();
  
      let nr = namaresto;
      let al = alamat;
      let j = jenis;
  
      console.log(namaresto, alamat, jenis)
  
      const options = {
          method:"POST",
          headers:{'Content-Type':'application/json'},
          body:JSON.stringify({namaresto:nr, alamat:al, jenis:j})
      }
    
      await fetch('http://localhost:3000/api/auth/data-usaha', options)
          .then(res=>res.json())
          .then((datas)=>{
            console.log(datas);
            if(datas.status)router.push('http://localhost:3000/homepage');
            else alert(datas.message);
          })
    
    }


    return (
        <>
        <Head>
            <title>GetPartner</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
        <div class=" box position-relative">
            <div class="position-absolute top-50 start-50 translate-middle">
                <div className={styles.logo}>
                    <Image 
                    src="/aset/login n signin aset/Getjob.svg" 
                    alt="logo"
                    width={150}
                    height={50}
                    />
                </div>

                <div className={styles.title}>
                    <p>
                        Anda Mendaftar Sebagai
                        <br/>
                        <span className={styles.highlight}>Merchant</span>
                        <br/>
                        <br/>
                        Isi Data Usaha Anda
                    </p>
                </div>

                <div className={styles.setup_main}>
                    <div className="merchant_field">
                        <input 
                        type="text" 
                        className={styles.setup_input} 
                        placeholder="Nama Rumah Makan"
                        onChange={(e) => setResto(e.target.value)}
                        />
                    </div>

                    <div className="merchant_field">
                        <input 
                        type="text" 
                        className={styles.setup_input} 
                        placeholder="Alamat Rumah Makan"
                        onChange={(e) => setAlamat(e.target.value)}
                        />
                    </div>

                    <div class="input-group mb-3" className={styles.non_text_group}>
                        <select 
                        class="form-select" 
                        className={styles.setup_select} 
                        id="inputGroupSelect01"
                        onChange={(e) => setJenis(e.target.value)}
                        >
                            <option selected>Jenis Resto</option>
                            <option value="1">Fast Food</option>
                            <option value="2">Casual Dining</option>
                            <option value="3">Cafe</option>
                            <option value="4">Fine Dining</option>
                            <option value="5">Takeaway Only</option>
                        </select>
                    </div>
            
                    <div class="input-group mb-3" className={styles.non_text_group}>
                        <label className={styles.non_text_group_text}>Foto Rumah Makan</label>
                        <input type="file" accept="image/*" className={styles.setup_upload}/>
                    </div>
                </div>

                <div class="form-check" className={styles.setup_check}>
                        <input type="checkbox" value="" className={styles.checkbox}/>
                        <label className={styles.check_label}>
                            Saya telah membaca dan menyetujui <span className={styles.snk}>Syarat & Ketentuan</span> dan siap menjadi Partner Resmi dari GetJob.
                        </label>
                </div>

                <div className={styles.buttons}>
                        <Link href="#"><button className={styles.setup_next_btn} onClick={(e) => handler(e)}>Selesai</button></Link>
                </div>
            </div>
        </div>
        </main>
        </>
    )
}

export async function getServerSideProps({req}){
    const session = await getSession({req})

    if(!session){
        return{
            redirect:{
                destination:'http://localhost:3000/daftar/merchant/data-diri',
                permanent:false
            }
        }
    }

    return {
        props: {session}
    }
}