import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/login n signin/Profile-setup.module.css'

export default function Merchant() {
    return (
        <>
        <Head>
            <title>GetPartner</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
        <div class=" box position-relative">
            <div class="position-absolute top-50 start-50 translate-middle">
                <div className={styles.logo}>
                    <Image 
                    src="/aset/login n signin aset/Getjob.svg" 
                    alt="logo"
                    width={150}
                    height={50}
                    />
                </div>

                <div className={styles.title}>
                    <p>
                        Anda Mendaftar Sebagai
                        <br/>
                        <span className={styles.highlight}>Merchant</span>
                        <br/>
                        <br/>
                        Isi Data Diri Anda
                    </p>
                </div>

                <div className={styles.setup_main}>
                    <div className="merchant_field">
                        <input type="text" className={styles.setup_input} placeholder="Nama Lengkap"/>
                    </div>

                    <div className="merchant_field">
                        <input type="text" className={styles.setup_input} placeholder="Alamat Email"/>
                    </div>

                    <div class="input-group mb-3" className={styles.non_text_group}>
                        <select class="form-select" className={styles.setup_select} id="inputGroupSelect01">
                            <option selected>Pilih Kota</option>
                            <option value="1">Jakarta</option>
                            <option value="2">Yogyakarta</option>
                            <option value="3">Solo</option>
                        </select>
                    </div>
            
                    <div class="input-group mb-3" className={styles.non_text_group}>
                        <label class="input-group-text" className={styles.non_text_group_text} for="inputGroupFile01">Foto KTP</label>
                        <input type="file" class="form-control" className={styles.setup_upload} id="inputGroupFile01" />
                    </div>
            
                    <div className="buttons">
                        <Link href="#"><button className={styles.setup_next_btn}>Lanjutkan</button></Link>
                    </div>
                </div>
            </div>
        </div>
        </main>
        </>
    )
}