import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GetPartner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="box position-relative" className="box">
        <div className="position-absolute top-50 start-50 translate-middle">
            <div className={styles.logo}>
              <Image 
              src='/aset/login n signin aset/Getjob.svg' 
              width={150} 
              height={50} 
              />
            </div>
        
            <div className={styles.login_main}>
                <div className="login_field">
                    <input type="text" className={styles.login_input} placeholder="Phone Number"/>
                </div>
        
                <div className="login_field">
                    <input type="password" className={styles.login_input} placeholder="Password"/>
                </div>
        
                <div className="buttons">
                    <Link href="#"><button className={styles.login_btn}>Masuk</button></Link>
                </div>
        
                <div className={styles.regisask}>
                    Belum punya akun? <Link href="/daftar" className="goregister">Daftar</Link>
                </div>
            </div>
        </div>
      </div>
    </>
  )
}
