import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GetPartner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div class=" box position-relative" className={styles.box}>
        <div class="position-absolute top-50 start-50 translate-middle">
            <div className={styles.logo}>
                <Image 
                src="/Getjob.png" 
                alt="logo1"
                width={150}
                height={50}
                />
            </div>
        
            <div className={styles.login_main}>
                <div class="login__field">
                    <i class="login__icon fas fa-user"></i>
                    <input type="text" className={styles.login__input} placeholder="Phone Number"/>
                </div>
        
                <div class="login__field">
                    <i class="login__icon fas fa-lock"></i>
                    <input type="password" className={styles.login__input} placeholder="Password"/>
                </div>

                <div class="login__field">
                    <i class="login__icon fas fa-lock"></i>
                    <input type="password" className={styles.login__input} placeholder="Confirm Password"/>
                </div>
        
                <div class="buttons">
                    <a href="/AfterLog/index2.html"><button className={styles.register__btn}>Register</button></a>
                </div>
        
                <div className={styles.regisask}>
                    Sudah punya akun? <a href="register.html" class="goregister"> Login</a>
                </div>
                
            </div>
        </div>
      </div>
      </main>
    </>
  )
}
