import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { Inter } from '@next/font/google';
import styles from '@/styles/setting.module.css';
import Link from 'next/link';
import Footer from '/components/footer';
import Navbar from '/components/navbar';
import { useState } from 'react';
import { useRouter } from 'next/router';
import { getSession, useSession, signOut } from "next-auth/react"

export default function Daftar() {

    const{ data:session } = useSession()
    function handleSignOut(){
        signOut()
    }


  return (
    <>
      <Head>
        <title>GetFull</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

    <div className={styles.setting_main}>
        <div className='setting_main'>
            <div className={styles.line1}><span class="icon">
                <Image 
                src="/aset/setting aset/getrich.svg" 
                alt="getrich"
                width={30}
                height={30}
                />
                </span>
                &nbsp;
                My GetRich
                <div className={styles.panah_ijo}>
                    <Image 
                        src='/aset/setting aset/panah ijo.svg' 
                        width={30} 
                        height={30} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}><span class="icon">
                <Image 
                src="/aset/setting aset/riwayat.svg" 
                alt="rwyt"
                width={30}
                height={30}
                />
                </span>
                &nbsp;
                Riwayat
                <div className={styles.panah_ijo}>
                    <Image 
                        src='/aset/setting aset/panah ijo.svg' 
                        width={30} 
                        height={30} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}><span class="icon">
                <Image 
                src="/aset/setting aset/bahasa.svg" 
                alt="bhs"
                width={30}
                height={30}
                />
                </span>
                &nbsp;
                Bahasa
                <div className={styles.panah_ijo}>
                    <Image 
                        src='/aset/setting aset/panah ijo.svg' 
                        width={30} 
                        height={30} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}><span class="icon">
                <Image 
                src="/aset/setting aset/privasi.svg" 
                alt="prvs"
                width={30}
                height={30}
                />
                </span>
                &nbsp;
                Privasi
                <div className={styles.panah_ijo}>
                    <Image 
                        src='/aset/setting aset/panah ijo.svg' 
                        width={30} 
                        height={30} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}><span class="icon">
                <Image 
                src="/aset/setting aset/syarat dan ketentuan.svg" 
                alt="sdk"
                width={30}
                height={30}
                />
                </span>
                &nbsp;
                Syarat dan Ketentuan
                <div className={styles.panah_ijo}>
                    <Image 
                        src='/aset/setting aset/panah ijo.svg' 
                        width={30} 
                        height={30} 
                    />
                </div>
            </div>
        </div>

        <div className="buttons">
                <Link href="/"><button onClick={handleSignOut} className={styles.logout_btn}>Logout</button></Link>
        </div>
        
      </div>
      <Footer/>
    </>
  )
}

export async function getServerSideProps({req}){
    const session = await getSession({req})

    if(!session){
        return{
            redirect:{
                destination:'http://localhost:3000',
                permanent:false
            }
        }
    }

    return {
        props: {session}
    }
}
