import Head from 'next/head';
import Navbar from 'components/navbarresto';
import AddEtalase from 'components/merchant_home/add_etalase';
import Footer from 'components/footer'
import styles from '@/styles/components/merchant/add_etalase/add_etalase.module.css'

export default function Etalase() {
  return (
    <>
    <Head>
        <title>GetFull</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <Navbar/>

    <div className='mt-3'>
        <h5 className='ms-4'>Etalase</h5>
    </div>

    <div className='default_etalase d-flex justify-content-center'>
      <div className={styles.etalase}>
        Makanan
      </div>
    </div>

    <div className='default_etalase d-flex justify-content-center'>
      <div className={styles.etalase}>
        Minuman
      </div>
    </div>

    <div className='d-flex justify-content-center'>
      <AddEtalase/>
    </div>
    
    <Footer/>
    </>
  );
}