import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Navbar from 'components/navbar'
import Footer from 'components/footer'
import Order from 'components/merchant_home/order'
import styles from '@/styles/merchant/homepage.module.css'

export default function Homepage() {
    return (
        <>
        <Head>
            <title>GetFull</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>

        <div className={styles.order}>
            <Order/>
        </div>

        <div className={styles.dummy}>
            <Image
            src='/dummy_history.svg' 
            width={230} 
            height={150} 
            />

            <Image
            src='/dummy_rating.svg' 
            width={140} 
            height={150} 
            />
        </div>

        <div className={styles.dummy}>
        <Image
            src='/dummy_graph.svg' 
            width={355} 
            height={230} 
            />
        </div>

        <Footer/>
        </>
    )
}