import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { Inter } from '@next/font/google';
import styles from '@/styles/inputproduct.module.css';
import Link from 'next/link';
import Footer from '/components/footer';
import Navbar from '/components/navbar';
import { useState } from 'react';
import { useRouter } from 'next/router';

export default function Daftar() {

  return (
    <>
      <Head>
        <title>GetFull</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      
        <div className={styles.yuk}>
            Yuk, isi informasi produkmu
        </div>
        
        <div className={styles.input_box}>
            <div class="input-group mb-3" className={styles.non_text_group}>
                <label className={styles.non_text_group_text}>Foto Produk</label>
                <input type="file" accept="image/*" className={styles.setup_upload}/>
            </div>

            <div className="merchant_field">
                <input 
                type="text" 
                className={styles.setup_input} 
                placeholder="Nama Produk"
                onChange={(e) => setName(e.target.value)}
                />
            </div>

            <div className="merchant_field">
                <input 
                type="text" 
                className={styles.setup_input} 
                placeholder="Harga (Rp)"
                onChange={(e) => setName(e.target.value)}
                />
            </div>

            <div className="merchant_field">
                <input 
                type="text" 
                className={styles.setup_input} 
                placeholder="Deskripsi Produk"
                onChange={(e) => setName(e.target.value)}
                />
            </div>

            <div class="input-group mb-3" className={styles.non_text_group}>
                <select 
                class="form-select" 
                className={styles.setup_select} 
                id="inputGroupSelect01"
                onChange={(e) => setKota(e.target.value)}
                >
                    <option selected>Etalase</option>
                    <option value="1">Makanan</option>
                    <option value="2">Minuman</option>
                </select>
            </div>

            <div class="input-group mb-3" className={styles.non_text_group}>
                <select 
                class="form-select" 
                className={styles.setup_select} 
                id="inputGroupSelect01"
                onChange={(e) => setKota(e.target.value)}
                >
                    <option selected>Status</option>
                    <option value="1">Aktif</option>
                    <option value="2">Non-Aktif</option>
                </select>
            </div>


            <div className="buttons">
                <button className={styles.tambah_btn}>Tambahkan Produk</button>
            </div>
        </div>

      <Footer/>
    </>
  )
}