import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/login n signin/Portal.module.css'

export default function Portal() {
    return (
        <>
        <Head>
            <title>GetPartner</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
        <div class=" box position-relative">
            <div class="position-absolute top-50 start-50 translate-middle">
                <div className={styles.logo}>
                    <Image 
                    src="/aset/login n signin aset/Getjob.svg" 
                    alt="logo"
                    width={150}
                    height={50}
                    />
                </div>
        
                <div className={styles.portal_main}>
                    <div class="sloganasik">
                        <h1>Selamat Datang di Pekerjaan yang ASIK</h1>
                    </div>

                    <div class="buttons">
                        <Link href="/daftar/merchant/data-diri"> 
                            <button className={styles.portal_btn}><span class="icon">
                                <Image 
                                src="/aset/login n signin aset/portal/marketstall.png" 
                                alt="logo1"
                                width={35}
                                height={35}
                                />
                                </span>
                                &nbsp;
                                Merchant Partnership
                            </button>
                        </Link>
                    </div>

                    <div class="buttons">
                        <Link href="/daftar/driver/data-diri">
                        <button className={styles.portal_btn}>
                            <span class="icon">
                            <Image 
                            src="/aset/login n signin aset/portal/deliverydining.png" 
                            alt="logo2"
                            width={35}
                            height={35}
                            />
                            </span>
                            &nbsp;
                            Driver Partnership
                        </button>
                        </Link>
                    </div>
                </div>
            </div>
        </div>
        </main>
        </>
    )
}